name: flutter_onnxruntime
description: "A new Flutter plugin project."
version: 1.0.0
homepage: https://github.com/masicai/flutter_onnxruntime
repository: https://github.com/masicai/flutter_onnxruntime

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.masicai.flutteronnxruntime
        pluginClass: FlutterOnnxruntimePlugin
      ios:
        pluginClass: FlutterOnnxruntimePlugin
      linux:
        pluginClass: FlutterOnnxruntimePlugin
      macos:
        pluginClass: FlutterOnnxruntimePlugin
