# Rules
line_length:
  warning: 150
  error: 150
  ignores_comments: true
  ignores_urls: true

# Paths to ignore during linting
excluded:
  - Pods
  - ios/Pods

# Disabled rules
disabled_rules:
  - function_parameter_count
  - function_body_length
  - file_length

# Customize rules
analyzer_rules:
  - unused_declaration
  - unused_import

# Opt-in rules
opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - missing_docs
  - trailing_whitespace
  - vertical_whitespace

# Rule customizations
force_cast: warning
force_try: warning

# Rules that support autocorrect
whitelist_rules:
  - closing_brace
  - comma
  - colon
  - empty_enum_arguments
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - leading_whitespace
  - opening_brace
  - return_arrow_whitespace
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - void_return
