name: C++ Lint

on:
  push:
    branches:
      - main
    paths:
      - 'linux/**/*.cc'
      - 'linux/**/*.h'
      - 'linux/**/*.cpp'
      - 'linux/**/*.hpp'
      # Add paths for other C++ files if needed, e.g.:
      # - 'cpp/**/*.cc'
      # - 'cpp/**/*.h'
  pull_request:
    branches:
      - main
    paths:
      - 'linux/**/*.cc'
      - 'linux/**/*.h'
      - 'linux/**/*.cpp'
      - 'linux/**/*.hpp'
      # - 'cpp/**/*.cc'
      # - 'cpp/**/*.h'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format
    
    - name: Run clang-format
      run: |
        find linux -name "*.cc" -o -name "*.h" -o -name "*.cpp" -o -name "*.hpp" | \
        grep -v "example/linux/flutter/" | \
        xargs clang-format -i --style=file
        
        # Check if any files were modified
        if ! git diff --quiet; then
          echo "C++ files were automatically formatted. Please run 'git add' and commit the changes."
          git diff
          exit 1
        fi
    
  cppcheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install cppcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck
    
    - name: Run cppcheck
      run: |
        cppcheck --enable=all --error-exitcode=1 --suppress=missingIncludeSystem \
        --xml --output-file=cppcheck-report.xml --suppress="*:example/linux/flutter/*" linux/
    
    - name: Upload cppcheck report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cppcheck-report
        path: cppcheck-report.xml