name: ONNX Runtime Linux Integration Tests

on:
  workflow_dispatch:
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]

jobs:
  linux_integration_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Enable Linux desktop support
        run: flutter config --enable-linux-desktop

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev liblzma-dev

      - name: Install Flutter dependencies
        run: |
          flutter pub get
          cd example
          flutter pub get

      - name: Verify model file exists
        run: |
          find . -name "addition_model.ort" || echo "Model not found!"
          ls -la example/assets/models || echo "Directory not found!"

      - name: Run integration tests on Linux
        run: |
          # Use the existing example app
          cd example
          
          # Run integration tests file by file (workaround for Flutter issue #135673)
          for test_file in integration_test/*.dart; do
            if [ -f "$test_file" ]; then
              flutter test "$test_file" -d linux
            fi
          done 